language: ruby #gem install -v 1.10.6 bundler --no-rdoc --no-ri bundle _1.10.6_ install
rvm:
  - 2.2.4
before_install:
  - gem install nokogiri -v '1.6.8.1'
  - gem install ffi -v '1.9.14'
  #- gem bundler -v '1.11.2' --no-rdoc --no-ri
  - gem install -v 1.10.6 bundler --no-rdoc --no-ri
  - bundle _1.10.6_ install
env:
  global:
  - secure: dY6UeC3ClCTp04p/fCLv49PNZpd/jDBX0d+pegVIFdBKMibWTIOUtHK29tMCP5WqoMmN9J0yiOT87MXDom39l6JFR6tqdxmYakAGvpube/q5jV9yVDBrCQt2LcV3kRKDGfEaErfYsNm0B1wBWvz/5NvIiMIDvY3hYXGzx78aYpf9frr+eE2TXpqx0DKzdvtOjRCXvROFSvv8Ye+FbPzyJumeiJ9PUUV41wc3OuVGKAN/zbE1vpJlozT/P3hpObtX+JQFz3gNA6Cms4A3iWO5rMVDyL1Vx6KqDFxvydYrST0bOzzgi9xb+bwBhQKfwLNbL8dJOjLapvCaxPaAgAZzHYAx8TiN0GYgo/M8vLOqQ6lN6TpDGIejh6ppXLXo5+bSWQPbFoEpurGBzT2AM/tTt6tB0U8h4Mg7W48qfb+T95KhVDmrE7BVSbLaqOVau2hqikvEXX23mLDjNMcKnWrNe00le+RZoFb9mzBcS3ims+8QmTG42dRZ6MN8fOB13vjd6+V7XgZdq8sfHeFztJvCN5kmVi9ZiFJpGEhUqkvT4bvNalw/B477PgCO//LyvRiK82WnnUayc8yW4xZHC3wgpd7TV07r1YPm8KWa3lmn3YGkSG2E/5HnZ5ELoCYFwqXKhOqWK3j69x13W07ujEZIgyaNA0dIgjdG9bItnfgxbns=
  - secure: YLeE3xVUF4yeTocXFMwnMtwp0FGmqccpYhKMM7PDcvux8MUxOGv0v5aZXpB8hoUF1TfEz1MDMl9F/ZcatooBWT+1kS3fHbiuHg18MKlJtiI7NQNYROlLmzM2i2JTAQhf4bJdCZ8lXxbb3F2Hg6dm2qGwD/CclldHQAGLDCD2fXTcjTze8ziS7xCUE91hRLNq/Ah/gbu5mjPvv7cBnZeURlTbQp+3mtrj5fYMCAwadaTXbU/Tq0ECNuZgvgwgp7ATmH+yD/XmNnqnrPapZRb84LOVsSVZ4ANgWWUDQQA73+U4tild9yg64PeAWrLl5NSF6/ycfE13FUgdWwE97vMGrhjb851aCiG2RiFaib7ko4sGq4n6gGNFr587xcJIS1jetSdebmWQcnniY7jwM635LUs1zTPamgcqhOy21sDM/uKM3FmH5T8QEiuERWUtKU/1VqMl2HmxTH3dEGY8dsHSrWP3ujHBem3r4pAZoCCiijXu3fe9FotaLu3JeeX71YqVvBs8R3a+b+d1juaCEktwvfHB/sH80usZUxjjLZS5kfKV5fsTAYCHznqC/WMUhb0irJdy3FEP7goUpoOJP+BhnulwO4lzKLjiw6uK/V2sGVpSceK5cv0WYjNIuqKVoPu8BhFDwKz0DeZvUR5o9qkvk4sW8KuxZd63IyDxlSYiNxo=
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
  - secure: ykxYo5Eq+33awTyM0bQO8Cf7RfXqDrbJFKlYm7cBEETzUR5xXwGHorj7GGDHjx2NwHsbHLNqGvbdrhr5cai+73Qr964bvkHKJCoEPxkEEjP9W6wSERzHtMW35RgE0w+tWBoS1vZz6N4CilkjS2nLargOthKpM8lqDWLl9I6ku8z9ofYbPHncYz1KWh7qspGIHy3etxZp2ZizGcs9OVhHDvQN14OkJrj3/5z4XvKfTSszmyIvFQ4rawFwHuIRtYPr5/tpRoc0QXN8c71J9COFyhpdvDqa+qp+ohweL7p+BLrm/cC2m3ClWe2LTOx8Pf0kyn2NwIk3vAEu9sYBvyEfO6gjGSVL9XE9BDvaJCol9bmAYDWeY08QdJOYNOYmD9i4znGk3tQyqGrHHDfQg6DXGDRQcTuUTDOV7t4yDTj/QJWufm480z+/yAbUafHtlQMNwpsa7QC/a/TebI0RKC3d0x74B3uHbkCWWEmjnCUcPlct6ArTgSn0AjztDu5xaHXy9Qpev/QK0hER+aOKgR+kR4jje6wuVCVNtA5uWW+z5GfbJhO/E+CO7N9dvou5rEhJNK4XQCwCItBbR2jyrR2ygnaebshlqwC2iewjRWSEEQoUFQEDFh/IsX4PPM4hLGjGwU6wtloWYZkV0O1M7EevCkheCOwEhQaHIBoibMP56sI=
deploy:
  provider: heroku
  api_key:
    secure: CIwtKLo5LU6bDsANOH3zFduPUp6Fr2epPD2DstSlGrTNBPk/FSW7cjbWVKtsY28g4GQAFma/r9irWDXIzzJL+NKIIK7rcaJzygZI9Kz5DczM3/uN+Tay3lS6zOCxLJlXSg8VgWXqmmlgEex8Hqf7907WUgg/Ut8BbEB/yWfjH7GYgK0IKlZEI5ihjuQfPML+hu4PLwxaFvuHEHszRpIJVvAnUCEj4+ShUoWz/Nv+INvSfImO6vlN+cGv60v8AxVKQm+LxIZkPEc8vH7W6CXnMoLBmU0vPeM0JLr0T4fP3VUPuFiOV51rj4hP3+3wQ15BO3blOVK4qQUdXsTQdFJ2DSU9Iv5FbquOF7nE9oaxTMK6ikrALCXJFcnQLWqx1VLsht7Tk2aXLjW+Tl49IT8VfSpcWAXIB+twE9qvvj/iEYRhxi6KXOhaqETYNT9fR8Ypf6oOES29sDT5H6OlGvJq4ewxuNmDYnB6bF8qM2DlaMMLbckVwyUehgMc6UQ4c0GHhr+6ACEVsiwwd5fUeEYFsT7pWtmXgrQOnX61oIGMuaYMG1VEIn96T++89o5sA1IFlIfAp3Ju51h+S6qqh1okwr+KpPGEap6L0PFP5mXKRC07smF1Hz+XWvZF2fOyfeYUObA425Aep0iKHurAkM2gLl+dqhLA3RHFH03+pfj4wSo=
  app: lawville
  on:
    repo: AfolabiOlaoluwa/LawVille
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
before_script:
- mysql -e 'create database strano_test'
- psql -c 'create database strano_test' -U postgres
